langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY}
      model-name: deepseek-chat
      log-requests: true
      log-responses: true

    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY}
      model-name: deepseek-chat
      log-requests: true
      log-responses: true

    embedding-model:
      api-key: sk-1a9447ee8a664656b5b05ea5d4039043
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: text-embedding-v3
      log-requests: true
      log-responses: true
      max-segments-per-batch: 10
#  community:
#    redis:
#      port: 6379
#      host: localhost

logging:
  level:
    dev.langchain4j: debug

spring:
  data:
    redis:
      port: 6379
      host: localhost

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306//volunteer?serverTimezone=Asia/Shanghai&userSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: lurui...

mybatis:
  configuration:
    map-underscore-to-camel-case: true
